name: PC Optimization Platform CI/CD

on:
    push:
        branches:
            - main

jobs: 
    Testing_Frontend: 

        runs-on: ubuntu-latest

        container: 
            image: node:20-alpine

        steps: 
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20

            # - name: Fix permissions
            #   working-directory: ./Frontend
            #   run: chmod -R +x node_modules/.bin || true
            
            - name: Install Dependencies
              working-directory: ./Frontend
              run: npm ci

            - name: Run Build Command
              working-directory: ./Frontend
              run: npm run build

    Tetsing_Backend: 

        runs-on: ubuntu-latest

        container: 
            image: python:3.11-slim

        steps: 
            - uses: actions/checkout@v3

            - name: Install Dependencies
              working-directory: ./Backend
              run: pip install -r requirements.txt

            - name: Run Command
              working-directory: ./Backend
              env: 
                DATABASE_URL: 'postgresql://postgres:1209@localhost:5432/pc_optimizer'

              run: uvicorn main:app & sleep 5






